[package]
name = "libsqlit"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = { version = "7.1.1", features = ["alloc"] }
eyre = "0.6.7"
color-eyre = "0.6.1"
thiserror = "1.0.30"

[lib]
name = "sqlit"
crate_type = ["dylib"]
